// Complaint constants

export const GET_ALL_COMPLAINTS = 'complaint/GET_ALL_COMPLAINTS';
export const GET_ALL_COMPLAINTS_ACTION = 'complaint/GET_ALL_COMPLAINTS_ACTION';
export const SET_ALL_COMPLAINTS = 'complaint/SET_ALL_COMPLAINTS';

export const GET_ALL_USER_COMPLAINTS_ACTION = 'complaint/GET_ALL_USER_COMPLAINTS_ACTION';

export const GET_COMPLAINT_DETAIL = 'complaint/GET_COMPLAINT_DETAIL';
export const GET_COMPLAINT_DETAIL_ACTION = 'complaint/GET_COMPLAINT_DETAIL_ACTION';
export const SET_COMPLAINT_DETAIL = 'complaint/SET_COMPLAINT_DETAIL';

export const CREATE_COMPLAINT_ACTION = 'complaint/CREATE_COMPLAINT_ACTION';
export const UPDATE_COMPLAINT_ACTION = 'complaint/UPDATE_COMPLAINT_ACTION';
export const DELETE_COMPLAINT_ACTION = 'complaint/DELETE_COMPLAINT_ACTION';

export const SET_COMPLAINT_COUNT = 'complaint/SET_COMPLAINT_COUNT';
export const GET_COMPLAINT_COUNT = 'complaint/GET_COMPLAINT_COUNT';
