// Department constants

export const GET_ALL_DEPARTMENTS = 'department/GET_ALL_DEPARTMENTS';
export const GET_ALL_DEPARTMENTS_ACTION = 'department/GET_ALL_DEPARTMENTS_ACTION';
export const SET_ALL_DEPARTMENTS = 'department/SET_ALL_DEPARTMENTS';

export const GET_DEPARTMENT_DETAIL = 'department/GET_DEPARTMENT_DETAIL';
export const GET_DEPARTMENT_DETAIL_ACTION = 'department/GET_DEPARTMENT_DETAIL_ACTION';
export const SET_DEPARTMENT_DETAIL = 'department/SET_DEPARTMENT_DETAIL';

export const CREATE_DEPARTMENT_ACTION = 'department/CREATE_DEPARTMENT_ACTION';
export const UPDATE_DEPARTMENT_ACTION = 'department/UPDATE_DEPARTMENT_ACTION';
export const DELETE_DEPARTMENT_ACTION = 'department/DELETE_DEPARTMENT_ACTION';

export const SET_DEPARTMENT_COUNT = 'department/SET_DEPARTMENT_COUNT';
export const GET_DEPARTMENT_COUNT = 'department/GET_DEPARTMENT_COUNT';
